name: CI
on:
  push:
    branches:
      - master
jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout
      uses: actions/checkout@master
    - run: yarn
    - run: yarn build

    - name: Build and Deploy
      uses: JamesIves/github-pages-deploy-action@master
      env:
        ACCESS_TOKEN: ${{ secrets.ACCESS_TOKEN }}
        BRANCH: gh-pages
        FOLDER: build
        BUILD_SCRIPT: yarn && yarn build

    - name: deploy file
        uses: webfactory/ssh-agent@v0.4.1
        with:
          username: 'root'
          server: '49.235.106.43'
          ssh_private_key: ${{ secrets.SSH_PRIVATE_KEY }} 
          local_path: './build/*'
          remote_path: '/usr/test'
          args: '-o ConnectTimeout=5'